version: 2
archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
builds:
  - goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    main: ./provider/cmd/pulumi-resource-fivetran
    binary: pulumi-resource-fivetran
    ldflags:
      - -X main.version={{.Tag}}
changelog:
  disable: true
